
spring:
  datasource:
      url: jdbc:h2:mem:phonebookdb
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update